final appWords = {
  'en': {
    'contacts': 'Contacts',
    'me': 'Me',
    'phone': 'Phone',
    'call': 'Call',
    'call_error': 'Failed to make call',
    'message': 'Message',
    'info': 'Info',
    'no_contacts': 'There are no contacts to show.',
    'update_success': 'Contact updated successfully',
    'update_error': 'Failed to update contact',
    'delete_success': 'Contact deleted successfully',
    'delete_error': 'Failed to delete contact',
    'add_contact': 'Add Contact',
    'add_error': 'Failed to add contact',
    'send_error': 'Failed to send SMS',
    'load_contacts_error': 'Failed to load contacts',
    'load_messages_error': 'Failed to load messages',
    'name': 'Name',
    'surname': 'Surname',
    'nickname': 'Nickname',
    'phone_number': 'Phone Number',
    'email': 'Email',
    'opt': 'opt',
    'name_error': 'Please enter a name',
    'surname_error': 'Please enter a surname',
    'nickname_error': 'This nickname is already in use',
    'phone_error': 'Please enter a phone number',
    'phone_invalid_error': 'Phone must be 10 digits long',
    'phone_exists_error': 'This phone number is already in use',
    'email_error': 'Please enter a valid email',
    'cancel': 'Cancel',
    'save': 'Save',
    'add': 'Add',
    'contact_info': 'Contact Info',
    'edit_name': 'Edit Name',
    'edit_surname': 'Edit Surname',
    'edit_nickname': 'Edit Nickname',
    'edit_phone_number': 'Edit Phone Number',
    'edit_email': 'Edit Email',
    'no_messages': 'No messages yet',
    'start_chat': 'Start a conversation',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'type_message': 'Type a message...',
  },
  'tr': {
    'contacts': 'Kişiler',
    'me': 'Ben',
    'phone': 'Telefon',
    'call': 'Ara',
    'call_error': 'Arama yapılamadı',
    'message': 'Mesaj',
    'info': 'Bilgi',
    'no_contacts': 'Gösterilecek kişi yok.',
    'update_success': 'Kişi başarıyla güncellendi',
    'update_error': 'Kişi güncellenemedi',
    'delete_success': 'Kişi başarıyla silindi',
    'delete_error': 'Kişi silinemedi',
    'add_contact': 'Kişi Ekle',
    'add_error': 'Kişi eklenemedi',
    'send_error': 'SMS gönderilemedi',
    'load_contacts_error': 'Kişiler yüklenemedi',
    'load_messages_error': 'Mesajlar yüklenemedi',
    'name': 'İsim',
    'surname': 'Soyisim',
    'nickname': 'Takma Ad',
    'phone_number': 'Telefon Numarası',
    'email': 'E-posta',
    'opt': 'seç',
    'name_error': 'Lütfen bir isim girin',
    'surname_error': 'Lütfen bir soyisim girin',
    'nickname_error': 'Bu takma ad zaten kullanılıyor',
    'phone_error': 'Lütfen bir telefon numarası girin',
    'phone_invalid_error': 'Telefon numarası 10 haneli olmalıdır',
    'phone_exists_error': 'Bu telefon numarası zaten kullanılıyor',
    'email_error': 'Lütfen geçerli bir e-posta girin',
    'cancel': 'İptal',
    'save': 'Kaydet',
    'add': 'Ekle',
    'contact_info': 'Kişi Bilgisi',
    'edit_name': 'İsmi Düzenle',
    'edit_surname': 'Soyismi Düzenle',
    'edit_nickname': 'Takma Adı Düzenle',
    'edit_phone_number': 'Telefon Numarasını Düzenle',
    'edit_email': 'E-postayı Düzenle',
    'no_messages': 'Henüz mesaj yok',
    'start_chat': 'Sohbete başla',
    'today': 'Bugün',
    'yesterday': 'Dün',
    'type_message': 'Mesaj yazın...',
  },
};
